"""Product naming for Remote Dragon."""

DISPLAY_NAME = "Remote Dragon"
INSTALL_DIRNAME = "RemoteDragon"
LEGACY_INSTALL_DIRNAME = "RemoteDesk"
RUN_VALUE = "RemoteDragonAgent"
LEGACY_RUN_VALUE = "RemoteDeskAgent"
TASK_NAME = "RemoteDragonAgent"
LEGACY_TASK_NAME = "RemoteDeskAgent"
CONFIG_DIRNAME = ".remote-dragon"
LEGACY_CONFIG_DIRNAME = ".remotedesk"
MUTEX_NAME = r"Local\RemoteDragonAgent"
DOCKER_IMAGE = "remote-dragon-relay"
ZIP_NAME = "RemoteDragon-windows.zip"
