"""Build the Windows release; stop immediately if a build step fails."""
import getpass
from pathlib import Path
import shutil
import subprocess
import sys
from urllib.parse import urlparse
import zipfile

ROOT = Path(__file__).resolve().parent


def main():
    if sys.platform != "win32":
        raise RuntimeError("Build these Windows executables on Windows with Python 3.10 or newer.")
    if sys.version_info < (3, 10):
        raise RuntimeError("Python 3.10 or newer is required.")
    import config

    relay = input(f"Relay URL [{config.RELAY_URL}]: ").strip() or config.RELAY_URL
    parsed = urlparse(relay)
    if parsed.scheme not in ("ws", "wss") or not parsed.hostname:
        raise ValueError("Relay URL must be ws://host:port/ws or wss://host/ws.")
    key = getpass.getpass("Network key (Enter keeps the existing key): ") or config.NETWORK_KEY
    if not key.strip():
        raise ValueError("Network key cannot be empty.")
    # repr handles quotes/backslashes/shell metacharacters without changing the key.
    (ROOT / "config.py").write_text(
        "# Generated by build_windows.py.\n"
        f"RELAY_URL = {relay!r}\nNETWORK_KEY = {key!r}\n", encoding="utf-8")

    def run(*args):
        subprocess.run([sys.executable, *args], cwd=ROOT, check=True)

    run("-m", "pip", "install", "pyinstaller>=6.9", "-r", "agent/requirements.txt",
        "-r", "controller/requirements.txt")
    run("-m", "PyInstaller", "--noconfirm", "--clean", "agent.spec")
    run("-m", "PyInstaller", "--noconfirm", "--clean", "controller.spec")
    dist = ROOT / "dist"
    for filename in ("install-agent.bat", "uninstall-agent.bat", "WINDOWS-QUICKSTART.md"):
        shutil.copy2(ROOT / filename, dist / filename)
    with zipfile.ZipFile(dist / "RemoteDragon-windows.zip", "w", zipfile.ZIP_DEFLATED) as archive:
        for filename in ("agent.exe", "controller.exe", "install-agent.bat",
                         "uninstall-agent.bat", "WINDOWS-QUICKSTART.md"):
            archive.write(dist / filename, filename)
    print("\nBuilt dist/agent.exe, dist/controller.exe and dist/RemoteDragon-windows.zip")


if __name__ == "__main__":
    try:
        main()
    except (OSError, RuntimeError, ValueError, subprocess.CalledProcessError) as exc:
        print(f"Build failed: {exc}", file=sys.stderr)
        sys.exit(1)
